name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'version'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'version'
  schedule:
    - cron: '0 * * * *'
jobs:
  lint:
    runs-on: ubuntu-latest
    name: "Run lint"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.3
          arguments: spotlessCheck --info
  test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      JAVA_OPTS: -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
      JVM_OPTS:  -Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8
    strategy:
      matrix:
        java: [ 17 ] # LTS versions + latest version
    name: "Run tests with JDK ${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.3
          arguments: test --info
  e2e:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - run: |
          docker buildx create --name amd-arm --driver docker-container --platform linux/amd64
          cd ./tools/e2e-test && make build && cd ../../
          ./tools/scripts/docker-build.sh
          ./tools/scripts/docker-compose-e2e-test.sh